### ISSUE TITLE
In this docker image, new topics are not created automatically.

### ISSUE THREAD

**Issue by glazkovalex** [hey-johnnypark/docker-kafka-zookeeper#9]
In this docker image, new topics are not created automatically. How do I set auto.create.topics.enable=true in this docker image so that new topics are created automatically?

**Comment by glazkovalex** [comment]
If I set the environment variable "AUTO_CREATE_TOPICS=true", then the string "**\n**auto.create.topics.enable=true" appears in $KAFKA_HOME/config/server.properties. Maybe if you remove the "\n" at the beginning, this option will work?

**Comment by hey-johnnypark** [comment]
Hi, yes I am happy for a pull request , thanks for spotting.

**Comment by obalunenko** [comment]
Hi @glazkovalex This repository is not maintained.
You can use this one: https://github.com/obalunenko/docker-kafka-zookeeper .
It already has pre-build images for all Kafka with zookeeper versions published on the official site https://kafka.apache.org/downloads

**Comment by glazkovalex** [comment]
Thank you, @belonenko!
I switched to the container: [confluentinc/cp-kafka ](https://hub.docker.com/r/confluentinc/cp-kafka ).
